language: python
python:
  - 3.6

sudo: required

services:
  - docker

install:
  - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> secrets.env
  - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> secrets.env
  - echo "DEBUG=$DEBUG" >> secrets.env
  - echo "SECRET_KEY=$SECRET_KEY" >> secrets.env
  - echo "API_KEY=$API_KEY" >> nginx/secrets.env

  - docker-compose build
  - docker-compose run image python manage.py migrate
  - docker-compose run image python manage.py loaddata data/db.json
  - pip install -r tests/requirements.txt

  - docker swarm init
  - docker service create --detach=false --name registry --publish published=5000,target=5000 registry:2
  - docker-compose push

before_script:
  - docker stack deploy --compose-file docker-compose.yml forestart
  - sleep 60
  - docker stack ls
  - docker service ls
  - docker service logs forestart_server
  - docker service logs forestart_image
  - docker service logs forestart_communication
  - docker service logs forestart_webui
  - ss -lntu

script:
  - pytest
