language: python
python:
  - 3.6

sudo: required

services:
  - docker

install:
  - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> secrets.env
  - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> secrets.env
  - echo "DEBUG=$DEBUG" >> secrets.env
  - echo "SECRET_KEY=$SECRET_KEY" >> secrets.env

  - docker-compose build
  - docker-compose run image python manage.py migrate
  - docker-compose run image python manage.py loaddata data/db.json
  - pip install -r tests/requirements.txt

before_script:
  - docker-compose up -d
  - sleep 30
  - docker-compose ps
  - docker-compose --version
  - ss -lntu
  - docker-compose logs

script:
  - pytest
