language: python
python:
  - 3.6

sudo: required

services:
  - docker

install:
  - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> image.secrets.env
  - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> image.secrets.env
  - echo "DEBUG=$DEBUG" >> image.secrets.env
  - echo "SECRET_KEY=$SECRET_KEY" >> image.secrets.env
  - echo "API_KEY=$API_KEY" >> server.secrets.env

  - ./scripts/start_dev.sh -b
  - pip install -r tests/requirements.txt

before_script:
  - docker-compose up -d
  - sleep 30
  - docker-compose ps
  - docker-compose --version
  - ss -lntu
  - docker-compose logs

script:
  - pytest
