version: '3'

services:
  webui:
    command: ["yarn", "start:dev"]
    volumes:
      - ./webui/src/:/code/src
  server:
    ports:
      - 80:80
      - 443:443
    command: ["nginx", "-g", "daemon off;"]
    links:
      - "webui:forestart_webui"
      - "image:forestart_image"
      - "communication:forestart_communication"
