version: '3'

services:
  server:
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/dist:/var/www
  api:
    build: backend/web_api
    command: ["gunicorn", "web_api.wsgi", "-b", "0.0.0.0:8000"]
    environment:
      - SECRET_KEY="t=r3o%4vz!_tl0--(+hu&h5+zo2q4i&csfg+hcewomd@hw9pebc"
      - DEBUG=False
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PORT=db
      - DATABASE_HOST=5432
    volumes:
      - ./backend/web_api:/code
    expose:
      - "8000"
    ports:
      - 8000:8000
