version: '3'

services:
  server:
    image: williamstrong/forestartserver
    ports:
      - 80:80
      - 443:443
    env_file:
      - server.secrets.env
  image:
    image: williamstrong/forestartimage
    env_file:
      - image.secrets.env
    command: ["gunicorn", "project.wsgi", "-b", "0.0.0.0:8000"]
  communication:
    image: williamstrong/forestartcommunication
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
  webui:
    image: williamstrong/forestartwebui
