version: '3'

services:
  webui:
    build: ./build/ForestArtWebUI
    command: ["run-script", "start:dev"]
    volumes:
      - ./build/ForestArtWebUI/src/:/code/src
  communication:
    build: ./build/ForestArtCommunication
    volumes:
      - ./build/ForestArtCommunication/:/code
      - /code/tmp
  image:
    build: ./build/ForestArtImage
    volumes:
      - ./build/ForestArtImage/:/code
  server:
    build: ./build/ForestArtServer
    ports:
      - 80:80
      - 443:443
    command: ["nginx", "-g", "daemon off;"]
    links:
      - "webui:forestart_webui"
      - "image:forestart_image"
      - "communication:forestart_communication"
