version: '3'

services:
  webui:
    build: ./tmp/ForestArtWebUI
    command: ["yarn", "start:dev"]
    volumes:
      - ./tmp/ForestArtWebUI/src/:/code/src
  communication:
    build: ./tmp/ForestArtCommunication
    volumes:
      - ./tmp/ForestArtCommunication/:/code
  image:
    build: ./tmp/ForestArtImage
    volumes:
      - ./tmp/ForestArtImage/:/code
  server:
    build: ./tmp/ForestArtServer
    ports:
      - 80:80
      - 443:443
    command: ["nginx", "-g", "daemon off;"]
    links:
      - "webui:forestart_webui"
      - "image:forestart_image"
      - "communication:forestart_communication"
