version: '3'

services:
  server:
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/dist:/var/www
  api:
    build: backend/web_api
    command: ["gunicorn", "web_api.wsgi", "-b", "0.0.0.0:8000"]
    env_file:
      - api-secrets.env
    volumes:
      - ./backend/web_api:/code
    expose:
      - "8000"
    ports:
      - 8000:8000
