version: '3'

services:
  server:
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/dist:/var/www
  api:
    build: backend/web_api
    env_file:
      - api-secrets.env
    command: ["gunicorn", "project.wsgi", "-b", "0.0.0.0:8000"]
    volumes:
      - ./backend/web_api:/code
  contact:
    build: backend/contact
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend/contact:/code
