version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  server:
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend/certbot/certs/etc:/etc/letsencrypt
      - ./backend/certbot/certs/data:/data/letsencrypt
      - ./frontend/dist:/var/www
    depends_on:
      - web
